variables:
  tenantID: '49dfc6a3-5fb7-49f4-adea-c54e725bb854' # teamtelstra.onmicrosoft.com
  vmImage: ''
  backendType: 'azurerm'
  # location: australiaeast

  proxy: 'http://proxy.nexus.telstra.com.au:8080'
  no_proxy: '169.254.169.254,*.azure.com'
# *.blob.core.windows.net,*.vaultcore.azure.net

  poolName_np: 'Linux Non-Production'
  poolName_prod: 'Linux Non-Production' #'Linux Production'  